<!DOCTYPE html>
<html lang="en">

<head>

  <!-- Contact me at jimeagle@gmail.com -->

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="James Eagle">
  <meta name="keywords" content="james,jim,eagle">

  <title>Jimeagle.com</title>

  <?= \Packaged\Dispatch\AssetManager::generateHtmlIncludes('css'); ?>

</head>

<body>

<?= $this->content(); ?>

<?= \Packaged\Dispatch\AssetManager::generateHtmlIncludes('js'); ?>

</body>
</html>
