<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="My website, made with Cubex, hosted on App Engine." />
  <meta name="author" content="James Eagle">
  <meta name="keywords" content="james,jim,eagle">

  <title>Jimeagle.uk</title>

  <meta property="og:title" content="Jimeagle.uk" />
  <meta property="og:type" content="profile" />
  <meta property="og:url" content="http://jimeagle.uk/" />
  <meta property="og:image" content="http://jimeagle.uk/favicon.ico" />

  <?= \Packaged\Dispatch\AssetManager::generateHtmlIncludes('css'); ?>

</head>
<body>

<div class="jumbotron">
  <div class="container text-primary">
    <h1>Jimeagle.uk</h1>
    <p>Hi, I'm Jim, a web developer in Hampshire, UK</p>
  </div>
</div>

<div class="container">
  <?= $this->content(); ?>
</div>

<?= \Packaged\Dispatch\AssetManager::generateHtmlIncludes('js'); ?>

</body>
</html>
