settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 8080
  host: "localhost"
schema:
  - name: Jimeagle
    path: .
    commands:
      install:
        status: true
      build:
        status: false
      run:
        status: true
    watcher:
      paths:
        - /
      extensions:
        - go
        - yaml
      ignored_paths:
        - .git
        - vendor
