<?php
/**
 * @var $this \Jleagle\Homepage\Application\Views\ErrorView
 */
?>

<section class="jumbotron">
  <div class="container">
    <h1 class="animated bounceInLeft">Jimeagle.uk</h1>
  </div>
</section>

<div id="main">
  <div class="container">

    <h1>404</h1>

    <p>Oops, looks like this page is no longer here!</p>
    <p>{{ link_to_route('home', 'Go Home') }}</p>

    <section id="contact">
    </section>

  </div>
</div>
