<?php
/**
 * @var $this \Jleagle\Homepage\Application\Views\HomeView
 */
?>

<header>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="intro-text">
          <hr class="star-light">
          <span class="name">Jim Eagle</span>
          <hr class="star-light">
          <span class="skills">
            <a href="https://github.com/Jleagle">GitHub</a> - <a href="mailto:jimeagle@gmail.com">Contact</a>
          </span>
        </div>
      </div>
    </div>
  </div>
</header>
