<?php
/**
 * @var $this \Jleagle\Homepage\Application\Views\HomeView
 */
?>

<?php if ($this->getError()){ ?>
  <div class="alert alert-danger" role="alert"><?= $this->getError() ?></div>
<?php } ?>

<h2>PHP Packages</h2>
<div class="well">
  <?= $this->getRepos() ?>
</div>

<h2>Projects</h2>
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-4">

    <a class="panel panel-primary" href="http://php-packages.com/" target="_blank">
      <div class="panel-heading">
        <h3 class="panel-title">PHP Packages</h3>
      </div>
      <div class="panel-body">Coming soon</div>
    </a>

  </div>
  <div class="col-xs-12 col-sm-6 col-md-4">

    <a class="panel panel-primary" href="http://brew-formulas.com/" target="_blank">
      <div class="panel-heading">
        <h3 class="panel-title">Brew Formulas</h3>
      </div>
      <div class="panel-body">Coming soon</div>
    </a>

  </div>
  <div class="col-xs-12 col-sm-6 col-md-4">

    <a class="panel panel-primary" target="_blank">
      <div class="panel-heading">
        <h3 class="panel-title">Spotify Helper</h3>
      </div>
      <div class="panel-body">Coming soon</div>
    </a>

  </div>
  <div class="col-xs-12 col-sm-6 col-md-4">

    <a class="panel panel-primary" target="_blank">
      <div class="panel-heading">
        <h3 class="panel-title">Reddit Battle</h3>
      </div>
      <div class="panel-body">Coming soon</div>
    </a>

  </div>
  <div class="col-xs-12 col-sm-6 col-md-4">

    <a class="panel panel-primary" target="_blank">
      <div class="panel-heading">
        <h3 class="panel-title">Steam Ranks</h3>
      </div>
      <div class="panel-body">Coming soon</div>
    </a>

  </div>
</div>


<h2>Email Me</h2>
<div class="well">

  <?= $this->getForm()->open() ?>

  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="form-group">
        <?= $this->getForm()->label('name', 'Name') ?>
        <?= $this->getForm()->input('name', ['class' => 'form-control']) ?>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="form-group">
        <?= $this->getForm()->label('email', 'Email') ?>
        <?= $this->getForm()->input('email', ['class' => 'form-control', 'type' => 'email']) ?>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="form-group">
        <?= $this->getForm()->label('body', 'Message') ?>
        <?= $this->getForm()->input('body', ['class' => 'form-control']) ?>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="form-group">
        <?= $this->getCaptcha()->html() ?>
      </div>
    </div>
  </div>

  <?= $this->getForm()->submit('Send', ['class' => 'btn btn-primary', 'id' => 'submit']) ?>

  <?= $this->getForm()->close() ?>

</div>
